---
version: "3.8"
services:
  mssql:
    container_name: mssql
    build:
      context: .
      target: schema-only
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - "./docker-image-test-data:/data:ro"
    environment:
      SA_PASSWORD: "P@ssw0rd"

networks:
  jore4:
